//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacytask
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Customers = new HashSet<Customer>();
            this.Suppliers = new HashSet<Supplier>();
        }
    
        public int P_id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParCode { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<long> Quantity { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Userid { get; set; }
        public Nullable<int> Ca_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplier> Suppliers { get; set; }
        public virtual Category Category { get; set; }
    }
}
